sequence_length: 20 # reduced
epochs: 1 # reduced
batch_size: 16 # reduced
validation_split: 0.1 # reduced
patience: 2 # reduced
model_name: "MusicTransformer"
tokenizer_name: "transformer_tokenizer"
num_raags_to_select: 1 #reduced
min_notes: 20 # reduced