sequence_length: 50
epochs: 5
batch_size: 64
validation_split: 0.2
patience: 10
model_name: "MusicTransformer"
tokenizer_name: "transformer_tokenizer"
num_raags_to_select: 5 # Change this to select number of raags or null to use all
